# Generated by Django 3.0 on 2019-12-12 23:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('balance', models.FloatField(default=0)),
                ('gender', models.CharField(max_length=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('is_on', models.BooleanField(default=False)),
                ('is_playing', models.BooleanField(default=False)),
                ('campaign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='terminals', to='fleet.Campaign')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='terminal', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('timesession', models.DurationField()),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='fleet.Campaign')),
                ('donator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='terminal.Donator')),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='terminal.Terminal')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('amount', models.FloatField()),
                ('currency', models.CharField(max_length=255)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='fleet.Campaign')),
                ('donator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='terminal.Donator')),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='terminal.Terminal')),
            ],
        ),
    ]
