#!/usr/bin/python3
# -*- coding: utf-8 -*-
# Author: Nicolas Flandrois
# Date:   Tue 16 June 2020 11:16:40
# Last Modified time: Tue 16 June 2020 12:06:10 

# Description:# Generated by Django 3.0.3 on 2020-03-09 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0004_auto_20200302_2224'),
        ('terminal', '0002_game_is_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminal',
            name='campaigns',
            field=models.ManyToManyField(related_name='terminals', to='fleet.Campaign'),
        ),
    ]
